"
Specialized feedback builder that applies accept/deny visual cues directly to the Roassal canvas background, rather than to a specific shape.
"
Class {
	#name : 'OPRSCanvasADFeedback',
	#superclass : 'OPRSAcceptDenyFeedbackBuilder',
	#category : 'OpenPonk-Roassal-CreationFeedback',
	#package : 'OpenPonk-Roassal',
	#tag : 'CreationFeedback'
}

{ #category : 'private' }
OPRSCanvasADFeedback >> feedbackFor: anEdge color: aColor [
	"not implemented"
]

{ #category : 'protocol' }
OPRSCanvasADFeedback >> remove [
	"not implemented"
]
