private - contents
createNewProjectIconContents
	"Private - Method generated with the content of the file File @ D:\OpenPonk\icons\idea\welcome\createNewProject.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAfElEQVR42mNgwAMuTVLQBmJZ
BnIBUHMjCBOr2BLdNiD/BAijicmC1GIzACTxFIj7oWxtKP8pzCtQuac4vYWk4CnUdmzsfnze
kEVSiAvLEgr1E3g0g+S0sdnaSEAjNoMawa6h2ACKvUDtQCQ/GilOSBQnZYozEx5vaeNTAwCa
VyUU/OC4vAAAAABJRU5ErkJggg=='