SystemOrganization addCategory: #'OpenPonk-Spec'!
SystemOrganization addCategory: 'OpenPonk-Spec-EditableDropList'!
SystemOrganization addCategory: 'OpenPonk-Spec-Form'!
SystemOrganization addCategory: 'OpenPonk-Spec-Palettes'!
SystemOrganization addCategory: 'OpenPonk-Spec-Toolbars'!
SystemOrganization addCategory: 'OpenPonk-Spec-Utils'!
SystemOrganization addCategory: 'OpenPonk-Spec-Windows'!
SystemOrganization addCategory: 'OpenPonk-Spec-Wizards'!
