icons
exampleAdornmentsIcon
	^ 'iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAABHklEQVR4XuXasREAIAgEQUuj
/yboBLUGJXDc4FICNv0REdPvnYb/BB/EzwfxQfx8EB/EzwfxQfx8EB/Ef4QP4ueD+CB+PogP
4ueD+CB+PogP4ueD+PkgPoifD+KD+PkgPoifD+KD+Pkgfj6ID+Lng/ggfj6ID+Lng/ggfj6I
nw/ig1yVma3tm+WD+CA+iA/ig/ggPogP4oP4ID6ID+KD+CA+iA/ig/ggPogP4oP4ID6ID+KD
+CA+iA/ig/ggn4wcqjl/5ODng/ggfj6ID+Lng/ggfj6Inw/ig/j5ID6Inw/ig/j5ID6Inw/i
54P4IH4+iA/i54P4IH4+iA/i54P4+SA+iJ8P4oP4+SA+iJ8P4oP4+SB+PogP4ueD+CB+5y0I
CSJCdIuZAgAAAABJRU5ErkJggg=='