SystemOrganization addCategory: #'OpenPonk-Core'!
SystemOrganization addCategory: 'OpenPonk-Core-Controllers'!
SystemOrganization addCategory: 'OpenPonk-Core-Figures'!
SystemOrganization addCategory: 'OpenPonk-Core-Icons'!
SystemOrganization addCategory: 'OpenPonk-Core-Models'!
SystemOrganization addCategory: 'OpenPonk-Core-Persistence'!
SystemOrganization addCategory: 'OpenPonk-Core-Tests'!
SystemOrganization addCategory: 'OpenPonk-Core-UICommands'!
