private - contents
dcOmlBoxIconContents
	"Private - Method generated with the content of the file File @ /home/peter/prog/dynacase/icons/dcOmlBox.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA
CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3gwRESQzmmlD8wAAABl0RVh0Q29tbWVudABD
cmVhdGVkIHdpdGggR0lNUFeBDhcAAABFSURBVDjLY2AY8oARSv+nUD9ZBvxnYGBgYKLUCyww
Rnh4OEmuWLlyJaZzyPECC7rowYMHUQyzt7dnJNq0oe+C/wwjEwAAMrgWCki0InUAAAAASUVO
RK5CYII='