SystemOrganization addCategory: #'DynaCASE-Core'!
SystemOrganization addCategory: 'DynaCASE-Core-Controllers'!
SystemOrganization addCategory: 'DynaCASE-Core-Figures'!
SystemOrganization addCategory: 'DynaCASE-Core-Icons'!
SystemOrganization addCategory: 'DynaCASE-Core-Models'!
SystemOrganization addCategory: 'DynaCASE-Core-Persistence'!
SystemOrganization addCategory: 'DynaCASE-Core-Tests'!
SystemOrganization addCategory: 'DynaCASE-Core-UICommands'!
