Class {
	#name : 'OPDiagramFigureMagentaFontColorCommand',
	#superclass : 'OPDiagramFigureFontColorCommand',
	#category : 'OpenPonk-Spec-Diagram-Figure-Commands',
	#package : 'OpenPonk-Spec',
	#tag : 'Diagram-Figure-Commands'
}

{ #category : 'as yet unclassified' }
OPDiagramFigureMagentaFontColorCommand >> color [

	^ Color magenta
]

{ #category : 'as yet unclassified' }
OPDiagramFigureMagentaFontColorCommand >> defaultMenuItemName [

	^ 'Magenta'
]
