Class {
	#name : 'OPDiagramFigureBlueFillColorCommand',
	#superclass : 'OPDiagramFigureFillColorCommand',
	#category : 'OpenPonk-Spec-Diagram-Figure-Commands',
	#package : 'OpenPonk-Spec',
	#tag : 'Diagram-Figure-Commands'
}

{ #category : 'as yet unclassified' }
OPDiagramFigureBlueFillColorCommand >> color [

	^ Color paleBlue
]

{ #category : 'as yet unclassified' }
OPDiagramFigureBlueFillColorCommand >> defaultMenuItemName [

	^ 'Blue'
]
