Class {
	#name : 'OPDiagramFigureOrangeFillColorCommand',
	#superclass : 'OPDiagramFigureFillColorCommand',
	#category : 'OpenPonk-Spec-Diagram-Figure-Commands',
	#package : 'OpenPonk-Spec',
	#tag : 'Diagram-Figure-Commands'
}

{ #category : 'as yet unclassified' }
OPDiagramFigureOrangeFillColorCommand >> color [

	^ Color paleOrange
]

{ #category : 'as yet unclassified' }
OPDiagramFigureOrangeFillColorCommand >> defaultMenuItemName [

	^ 'Orange'
]
