Class {
	#name : #OPDiagramFigureMagentaStrokeColorCommand,
	#superclass : #OPDiagramFigureStrokeColorCommand,
	#category : #'OpenPonk-Spec-Diagram-Figure-Commands'
}

{ #category : #'as yet unclassified' }
OPDiagramFigureMagentaStrokeColorCommand >> color [

	^ Color magenta
]

{ #category : #'as yet unclassified' }
OPDiagramFigureMagentaStrokeColorCommand >> defaultMenuItemName [

	^ 'Magenta'
]
