Class {
	#name : 'OPDiagramFigureRedFillColorCommand',
	#superclass : 'OPDiagramFigureFillColorCommand',
	#category : 'OpenPonk-Spec-Diagram-Figure-Commands',
	#package : 'OpenPonk-Spec',
	#tag : 'Diagram-Figure-Commands'
}

{ #category : 'as yet unclassified' }
OPDiagramFigureRedFillColorCommand >> color [

	^ Color paleRed
]

{ #category : 'as yet unclassified' }
OPDiagramFigureRedFillColorCommand >> defaultMenuItemName [

	^ 'Red'
]
