Class {
	#name : 'OPDiagramFigureYellowFontColorCommand',
	#superclass : 'OPDiagramFigureFontColorCommand',
	#category : 'OpenPonk-Spec-Diagram-Figure-Commands',
	#package : 'OpenPonk-Spec',
	#tag : 'Diagram-Figure-Commands'
}

{ #category : 'as yet unclassified' }
OPDiagramFigureYellowFontColorCommand >> color [

	^ Color yellow
]

{ #category : 'as yet unclassified' }
OPDiagramFigureYellowFontColorCommand >> defaultMenuItemName [

	^ 'Yellow'
]
