Class {
	#name : 'OPDiagramFigureRedFontColorCommand',
	#superclass : 'OPDiagramFigureFontColorCommand',
	#category : 'OpenPonk-Spec-Diagram-Figure-Commands',
	#package : 'OpenPonk-Spec',
	#tag : 'Diagram-Figure-Commands'
}

{ #category : 'as yet unclassified' }
OPDiagramFigureRedFontColorCommand >> color [

	^ Color red
]

{ #category : 'as yet unclassified' }
OPDiagramFigureRedFontColorCommand >> defaultMenuItemName [

	^ 'Red'
]
