Class {
	#name : 'OPDiagramFigureWhiteStrokeColorCommand',
	#superclass : 'OPDiagramFigureStrokeColorCommand',
	#category : 'OpenPonk-Spec-Diagram-Figure-Commands',
	#package : 'OpenPonk-Spec',
	#tag : 'Diagram-Figure-Commands'
}

{ #category : 'as yet unclassified' }
OPDiagramFigureWhiteStrokeColorCommand >> color [

	^ Color white
]

{ #category : 'as yet unclassified' }
OPDiagramFigureWhiteStrokeColorCommand >> defaultMenuItemName [

	^ 'White'
]
