Class {
	#name : 'OPDiagramFigureBlackStrokeColorCommand',
	#superclass : 'OPDiagramFigureStrokeColorCommand',
	#category : 'OpenPonk-Spec-Diagram-Figure-Commands',
	#package : 'OpenPonk-Spec',
	#tag : 'Diagram-Figure-Commands'
}

{ #category : 'as yet unclassified' }
OPDiagramFigureBlackStrokeColorCommand >> color [

	^ Color black
]

{ #category : 'as yet unclassified' }
OPDiagramFigureBlackStrokeColorCommand >> defaultMenuItemName [

	^ 'Black'
]
