Class {
	#name : 'OPDiagramFigureWhiteFontColorCommand',
	#superclass : 'OPDiagramFigureFontColorCommand',
	#category : 'OpenPonk-Spec-Diagram-Figure-Commands',
	#package : 'OpenPonk-Spec',
	#tag : 'Diagram-Figure-Commands'
}

{ #category : 'as yet unclassified' }
OPDiagramFigureWhiteFontColorCommand >> color [

	^ Color white
]

{ #category : 'as yet unclassified' }
OPDiagramFigureWhiteFontColorCommand >> defaultMenuItemName [

	^ 'White'
]
