Class {
	#name : 'OPDiagramFigureGreenStrokeColorCommand',
	#superclass : 'OPDiagramFigureStrokeColorCommand',
	#category : 'OpenPonk-Spec-Diagram-Figure-Commands',
	#package : 'OpenPonk-Spec',
	#tag : 'Diagram-Figure-Commands'
}

{ #category : 'as yet unclassified' }
OPDiagramFigureGreenStrokeColorCommand >> color [

	^ Color green
]

{ #category : 'as yet unclassified' }
OPDiagramFigureGreenStrokeColorCommand >> defaultMenuItemName [

	^ 'Green'
]
