Class {
	#name : 'OPDiagramFigureOrangeFontColorCommand',
	#superclass : 'OPDiagramFigureFontColorCommand',
	#category : 'OpenPonk-Spec-Diagram-Figure-Commands',
	#package : 'OpenPonk-Spec',
	#tag : 'Diagram-Figure-Commands'
}

{ #category : 'as yet unclassified' }
OPDiagramFigureOrangeFontColorCommand >> color [

	^ Color orange
]

{ #category : 'as yet unclassified' }
OPDiagramFigureOrangeFontColorCommand >> defaultMenuItemName [

	^ 'Orange'
]
