Class {
	#name : 'OPDiagramFigureRedStrokeColorCommand',
	#superclass : 'OPDiagramFigureStrokeColorCommand',
	#category : 'OpenPonk-Spec-Diagram-Figure-Commands',
	#package : 'OpenPonk-Spec',
	#tag : 'Diagram-Figure-Commands'
}

{ #category : 'as yet unclassified' }
OPDiagramFigureRedStrokeColorCommand >> color [

	^ Color red
]

{ #category : 'as yet unclassified' }
OPDiagramFigureRedStrokeColorCommand >> defaultMenuItemName [

	^ 'Red'
]
