Class {
	#name : 'OPDiagramFigureGreenFillColorCommand',
	#superclass : 'OPDiagramFigureFillColorCommand',
	#category : 'OpenPonk-Spec-Diagram-Figure-Commands',
	#package : 'OpenPonk-Spec',
	#tag : 'Diagram-Figure-Commands'
}

{ #category : 'as yet unclassified' }
OPDiagramFigureGreenFillColorCommand >> color [

	^ Color paleGreen
]

{ #category : 'as yet unclassified' }
OPDiagramFigureGreenFillColorCommand >> defaultMenuItemName [

	^ 'Green'
]
