Class {
	#name : 'OPDiagramFigureBlackFontColorCommand',
	#superclass : 'OPDiagramFigureFontColorCommand',
	#category : 'OpenPonk-Spec-Diagram-Figure-Commands',
	#package : 'OpenPonk-Spec',
	#tag : 'Diagram-Figure-Commands'
}

{ #category : 'as yet unclassified' }
OPDiagramFigureBlackFontColorCommand >> color [

	^ Color black
]

{ #category : 'as yet unclassified' }
OPDiagramFigureBlackFontColorCommand >> defaultMenuItemName [

	^ 'Black'
]
