Class {
	#name : 'OPDiagramFigureBlueFontColorCommand',
	#superclass : 'OPDiagramFigureFontColorCommand',
	#category : 'OpenPonk-Spec-Diagram-Figure-Commands',
	#package : 'OpenPonk-Spec',
	#tag : 'Diagram-Figure-Commands'
}

{ #category : 'as yet unclassified' }
OPDiagramFigureBlueFontColorCommand >> color [

	^ Color blue
]

{ #category : 'as yet unclassified' }
OPDiagramFigureBlueFontColorCommand >> defaultMenuItemName [

	^ 'Blue'
]
