Class {
	#name : 'OPDiagramFigureYellowFillColorCommand',
	#superclass : 'OPDiagramFigureFillColorCommand',
	#category : 'OpenPonk-Spec-Diagram-Figure-Commands',
	#package : 'OpenPonk-Spec',
	#tag : 'Diagram-Figure-Commands'
}

{ #category : 'as yet unclassified' }
OPDiagramFigureYellowFillColorCommand >> color [

	^ Color paleYellow
]

{ #category : 'as yet unclassified' }
OPDiagramFigureYellowFillColorCommand >> defaultMenuItemName [

	^ 'Yellow'
]
