Class {
	#name : 'OPDiagramFigureMagentaFillColorCommand',
	#superclass : 'OPDiagramFigureFillColorCommand',
	#category : 'OpenPonk-Spec-Diagram-Figure-Commands',
	#package : 'OpenPonk-Spec',
	#tag : 'Diagram-Figure-Commands'
}

{ #category : 'as yet unclassified' }
OPDiagramFigureMagentaFillColorCommand >> color [

	^ Color paleMagenta
]

{ #category : 'as yet unclassified' }
OPDiagramFigureMagentaFillColorCommand >> defaultMenuItemName [

	^ 'Magenta'
]
