"
Context menu command that resets the stroke color of the selected Roassal shape to its default value based on the element's style properties.
"
Class {
	#name : 'OPDiagramFigureDefaultStrokeColorCommand',
	#superclass : 'OPDiagramFigureStrokeColorCommand',
	#traits : 'OPTRoassalShapeDefaultColorCommand',
	#classTraits : 'OPTRoassalShapeDefaultColorCommand classTrait',
	#category : 'OpenPonk-Spec-Commands-RoassalShape',
	#package : 'OpenPonk-Spec',
	#tag : 'Commands-RoassalShape'
}
