"
Context menu command that resets the font color of the selected Roassal shape to its default value based on the element's style properties.
"
Class {
	#name : 'OPDiagramFigureDefaultFontColorCommand',
	#superclass : 'OPDiagramFigureFontColorCommand',
	#traits : 'OPTRoassalShapeDefaultColorCommand',
	#classTraits : 'OPTRoassalShapeDefaultColorCommand classTrait',
	#category : 'OpenPonk-Spec-Commands-RoassalShape',
	#package : 'OpenPonk-Spec',
	#tag : 'Commands-RoassalShape'
}
