"
Commander menu group that organizes commands responsible for toggling the visibility or presentation states of various shape components.
"
Class {
	#name : 'OPToggleRoassalShapeMenuGroup',
	#superclass : 'CmdMenuGroup',
	#category : 'OpenPonk-Spec-Commands-RoassalShape',
	#package : 'OpenPonk-Spec',
	#tag : 'Commands-RoassalShape'
}

{ #category : 'accessing' }
OPToggleRoassalShapeMenuGroup >> name [
	^ 'Show/hide'
]
