"
Commander activation strategy for commands that populate the main OpenPonk workbench top menu toolbar, typically handling project-level operations and dynamically active editor actions.
"
Class {
	#name : 'OPWorkbenchActivation',
	#superclass : 'CmdMenuCommandActivationStrategy',
	#category : 'OpenPonk-Spec-Commands-Workbench',
	#package : 'OpenPonk-Spec',
	#tag : 'Commands-Workbench'
}
