SystemOrganization addCategory: #'DynaCASE-Roassal2'!
SystemOrganization addCategory: 'DynaCASE-Roassal2-Builders'!
SystemOrganization addCategory: 'DynaCASE-Roassal2-Core'!
SystemOrganization addCategory: 'DynaCASE-Roassal2-Examples'!
SystemOrganization addCategory: 'DynaCASE-Roassal2-Interactivity'!
SystemOrganization addCategory: 'DynaCASE-Roassal2-Shapes'!
SystemOrganization addCategory: 'DynaCASE-Roassal2-Tests'!
