"
I store metadata for the OpenPonk-Morphic package. This package contains Morphic-specific UI extensions, custom widgets, and overrides used to tailor the underlying Pharo Morphic interface for OpenPonk's specific visual requirements.
"
Class {
	#name : 'ManifestOpenPonkMorphic',
	#superclass : 'PackageManifest',
	#category : 'OpenPonk-Morphic-Manifest',
	#package : 'OpenPonk-Morphic',
	#tag : 'Manifest'
}
