SystemOrganization addCategory: #'DynaCASE-UMLClass'!
SystemOrganization addCategory: 'DynaCASE-UMLClass-Controllers'!
SystemOrganization addCategory: 'DynaCASE-UMLClass-Examples'!
SystemOrganization addCategory: 'DynaCASE-UMLClass-Figures'!
SystemOrganization addCategory: 'DynaCASE-UMLClass-Layouting'!
SystemOrganization addCategory: 'DynaCASE-UMLClass-Models'!
SystemOrganization addCategory: 'DynaCASE-UMLClass-Parsers'!
