private - contents
exportIconContents
	"Private - Method generated with the content of the file File @ D:\OpenPonk\icons\idea\export.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABP0lEQVR42mP4//8/Awh3dXXh
xXpT7IX0pzlu05viIAPiw/QxIBnwHwc+U9vd4Gkyx/OU5WK//yZzPS7pTLbnJ9aAMy1dba4m
s7x2Wa8K/e+4Ofa/zeqw/4Zz3PdqTbRjw2UA3NnqfdaMutOdlpgvC/zvANTsvCPxv8OW2P8W
y4P+6053XgKSx2uA5hSHdqPFvv+tN0T+t9sa999+W/x/eyAN4oPEQfJ4DUDGlhuj/ltvifkP
ogkFIlYDjFYG/jffGPEfRJNlgM5iry9G64L/6yzxIt0A+V4zFs2Fbt/1V/v911ro9pZ0A3pM
gjTmO/3XWeH5X3Ou016SDJBq0bFTnGj6SmOhw3/NxU5fAybGZBFlgESDhqFUi/YsuV7DN8oz
LE+ozbNty+orTAIlLrICEYrPwNSQa8B/YgwgBlPPAABeEDpGXrZK1gAAAABJRU5ErkJggg=='