private - contents
layoutIconContents
	"Private - Method generated with the content of the file File @ D:\OpenPonk\icons\idea\layout.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA6UlEQVR42mP4//8/AyWYITIy
EiteXRP6f119GE4MksdmQBEQvwTiAzu7w/8fmhKJE4Pk0Q1IBOLHQGwC4u/rC/l/clb4fyAb
TKNjkDy6AdeAOAjG39np+//IlACcGCSPbsAfIOaE8bc2uf0/0OuJE4PkQeqQDfiPK0DRsAAQ
bwVifpgB06CaYXgaHs3MQLwXqm4PiA8T3AMVBEmy4jFgKrplMAl+qLMEifQG3LtEJxokzZzQ
AIcYAIoKYhINkgFB0ChHGEBMooFqMIImtiRUFxCRaICK9wPxKyAuRQ4PsAHEJhpsmIHS7AwA
I+sBKc+7H3oAAAAASUVORK5CYII='