SystemOrganization addCategory: #'DynaCASE-Spec'!
SystemOrganization addCategory: 'DynaCASE-Spec-EditableDropList'!
SystemOrganization addCategory: 'DynaCASE-Spec-Palettes'!
SystemOrganization addCategory: 'DynaCASE-Spec-Toolbars'!
SystemOrganization addCategory: 'DynaCASE-Spec-Utils'!
SystemOrganization addCategory: 'DynaCASE-Spec-Windows'!
SystemOrganization addCategory: 'DynaCASE-Spec-Wizards'!
