"
I store metadata for the OpenPonk-Tools package. This package contains development, debugging, and IDE integration utilities for OpenPonk, including extensions for the Calypso system browser and DrTests to facilitate LLM-assisted debugging and code exportation.
"
Class {
	#name : 'ManifestOpenPonkTools',
	#superclass : 'PackageManifest',
	#category : 'OpenPonk-Tools-Manifest',
	#package : 'OpenPonk-Tools',
	#tag : 'Manifest'
}
