"
Idea Icons

https://plugins.jetbrains.com/plugin/7285-idea-2016-2-icon-pack
https://plugins.jetbrains.com/plugin/10777-legacy-icon-pack-for-intellij-2018-2-
"
Class {
	#name : #OPIdeaIcons,
	#superclass : #Object,
	#category : #'OpenPonk-Core-Icons'
}

{ #category : #accessing }
OPIdeaIcons >> license [
	^ 'Copyright 2012 Konstantin Bulenkov

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.'
]
