name: Nightly

on:
  workflow_dispatch:
    inputs:
      build-dependent:
        description: 'Should build dependent repositories?'
        required: false
        default: false
  push:
    branches:
      - 'master'

env:
  REPOSITORY_NAME: '${{ github.event.repository.name }}'
  PROJECT_NAME: 'openponk-${{ github.event.repository.name }}'
  VERSION: 'nightly'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  cache-name: zip-cache
  RUN_ID: ${{ github.run_id }}

jobs:
  OP:
    uses: OpenPonk/ci-scripts/.github/workflows/test-nightly.yml@master
    secrets:
      WORKFLOW_ACCESS_TOKEN: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
